-- Create code_assignments table
CREATE TABLE IF NOT EXISTS code_assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT UNIQUE NOT NULL,
  ip_address TEXT,
  assigned_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert codes Code01 through Code99
INSERT INTO code_assignments (code, ip_address, assigned_at) VALUES
('Code01', NULL, NULL),
('Code02', NULL, NULL),
('Code03', NULL, NULL),
('Code04', NULL, NULL),
('Code05', NULL, NULL),
('Code06', NULL, NULL),
('Code07', NULL, NULL),
('Code08', NULL, NULL),
('Code09', NULL, NULL),
('Code10', NULL, NULL),
('Code11', NULL, NULL),
('Code12', NULL, NULL),
('Code13', NULL, NULL),
('Code14', NULL, NULL),
('Code15', NULL, NULL),
('Code16', NULL, NULL),
('Code17', NULL, NULL),
('Code18', NULL, NULL),
('Code19', NULL, NULL),
('Code20', NULL, NULL),
('Code21', NULL, NULL),
('Code22', NULL, NULL),
('Code23', NULL, NULL),
('Code24', NULL, NULL),
('Code25', NULL, NULL),
('Code26', NULL, NULL),
('Code27', NULL, NULL),
('Code28', NULL, NULL),
('Code29', NULL, NULL),
('Code30', NULL, NULL),
('Code31', NULL, NULL),
('Code32', NULL, NULL),
('Code33', NULL, NULL),
('Code34', NULL, NULL),
('Code35', NULL, NULL),
('Code36', NULL, NULL),
('Code37', NULL, NULL),
('Code38', NULL, NULL),
('Code39', NULL, NULL),
('Code40', NULL, NULL),
('Code41', NULL, NULL),
('Code42', NULL, NULL),
('Code43', NULL, NULL),
('Code44', NULL, NULL),
('Code45', NULL, NULL),
('Code46', NULL, NULL),
('Code47', NULL, NULL),
('Code48', NULL, NULL),
('Code49', NULL, NULL),
('Code50', NULL, NULL),
('Code51', NULL, NULL),
('Code52', NULL, NULL),
('Code53', NULL, NULL),
('Code54', NULL, NULL),
('Code55', NULL, NULL),
('Code56', NULL, NULL),
('Code57', NULL, NULL),
('Code58', NULL, NULL),
('Code59', NULL, NULL),
('Code60', NULL, NULL),
('Code61', NULL, NULL),
('Code62', NULL, NULL),
('Code63', NULL, NULL),
('Code64', NULL, NULL),
('Code65', NULL, NULL),
('Code66', NULL, NULL),
('Code67', NULL, NULL),
('Code68', NULL, NULL),
('Code69', NULL, NULL),
('Code70', NULL, NULL),
('Code71', NULL, NULL),
('Code72', NULL, NULL),
('Code73', NULL, NULL),
('Code74', NULL, NULL),
('Code75', NULL, NULL),
('Code76', NULL, NULL),
('Code77', NULL, NULL),
('Code78', NULL, NULL),
('Code79', NULL, NULL),
('Code80', NULL, NULL),
('Code81', NULL, NULL),
('Code82', NULL, NULL),
('Code83', NULL, NULL),
('Code84', NULL, NULL),
('Code85', NULL, NULL),
('Code86', NULL, NULL),
('Code87', NULL, NULL),
('Code88', NULL, NULL),
('Code89', NULL, NULL),
('Code90', NULL, NULL),
('Code91', NULL, NULL),
('Code92', NULL, NULL),
('Code93', NULL, NULL),
('Code94', NULL, NULL),
('Code95', NULL, NULL),
('Code96', NULL, NULL),
('Code97', NULL, NULL),
('Code98', NULL, NULL),
('Code99', NULL, NULL);

-- Enable Row Level Security (optional but recommended)
ALTER TABLE code_assignments ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read for available codes
CREATE POLICY "Allow public to read available codes" ON code_assignments
  FOR SELECT USING (true);

-- Create policy to allow public to update codes (assign IP)
CREATE POLICY "Allow public to update codes" ON code_assignments
  FOR UPDATE USING (true);
